# Generated by Django 4.0.10 on 2023-06-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_birth_date_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(choices=[(False, 'Offline'), (True, 'Online')], default=False, verbose_name='Статус'),
        ),
    ]
